### ISSUE TITLE
Qt5: Audio in Training is cut off early swallowing parts of  the tone output

### ISSUE THREAD

**Issue by hvoigt** [hardaker/CuteCW#12] opened 2016-06-14 21:42 UTC
I just compiled the convert-to-qt5 branch on my Ubuntu 15.10 machine and found that the audio seems to stop early. So e.g. for the k you only hear -. and the last dah is swallowed. I hacked a quick workaround which I am going to attach as a demonstration. The proper fix should probably not stop the audio so early I guess.

Here is the diff:

```
diff --git a/Morse.cpp b/Morse.cpp
index 57199d0..2749967 100644
--- a/Morse.cpp
+++ b/Morse.cpp
@@ -266,6 +266,14 @@ QTime Morse::playIt(QChar c, bool addLeadInPause) {
         add(pause());  // allows audio device to kick in (otherwise distortion can occur)
     m_leadInPause = sequenceTime();
     add(c, false); // add the pause in maybePlaySequence so it can calculate the sequence end
+
+    /* add a letter pause twice so audio does not stop early (cutting of
+     * the last dit or dah).
+     * This is a workaround and we should probably just let the audio
+     * run a little longer.
+     */
+    add(m_letterPause);
+    add(m_letterPause);
     return maybePlaySequence(true);
 }
```

This fixes the issue for my use case.

**Comment by barjac** [comment] 2017-10-31 11:10
I  also reported this issue here https://github.com/hardaker/CuteCW/issues/10#issue-34261261.
I will test your workaround. Thanks

**Comment by barjac** [comment] 2017-11-05 21:56
The patch seems already added in current sources with one  add(m_letterPause);  commented out, however with one or two the issue is not fixed.
Using 'read to me' mode the word 'a' is truncated, as is the 's' in 'is' - it seems that the shorter the word is the more likely it is to be corrupted .

**Comment by martinling** [comment] 2019-04-17 20:03
I have a fix for this here: https://github.com/rhaamo/CuteCW/pull/1

**Comment by barjac** [comment] 2019-04-18 21:18
This issue seems fixed after patching with the above fix. Thanks!
Any chance of fixing the handling of punctuation in the "read to me" mode? That would be great!

**Comment by hardaker** [comment] 2022-05-06 19:36
I've solved this in the main branch with qt6 by continually playing blank sounds, which solves the issue of starting sounds getting truncated too.

**Closed by hardaker** 2022-05-06 19:36 UTC
